name: monappmealplanning
description: "A Flutter application for meal planning."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25
  flutter_secure_storage: ^9.0.0
  logging: ^1.2.0
  firebase_storage: ^12.4.6
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  uuid: ^4.4.0
  
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/hrira.png
    - assets/images/google_logo.png
    
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
  # Correct indentation

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
