// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3zI75efJCF9XBNw7Z3ObymDFskqOV8c',
    appId: '1:917835733769:web:1807d77cde2317a62051d8',
    messagingSenderId: '917835733769',
    projectId: 'monappmealplanning',
    authDomain: 'monappmealplanning.firebaseapp.com',
    storageBucket: 'monappmealplanning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI0kI1Tt5o6L1xxZJQQNBuYhflwiDELWo',
    appId: '1:917835733769:android:517ca3e287f8f5ba2051d8',
    messagingSenderId: '917835733769',
    projectId: 'monappmealplanning',
    storageBucket: 'monappmealplanning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtC9-2B35RuGY9xgzA1zwF0g9EeEj-TU',
    appId: '1:917835733769:ios:f0e868e532e322c92051d8',
    messagingSenderId: '917835733769',
    projectId: 'monappmealplanning',
    storageBucket: 'monappmealplanning.firebasestorage.app',
    iosBundleId: 'com.example.monappmealplanning',
  );
}
